php-web:
  image: abhayagiri/php-7.0-apache:latest
  ports:
    - "9090:80"
  volumes:
    - ./dist:/var/www/html
  links:
    - php-mysql

php-nginx:
  image: daocloud.io/library/nginx:1.7.10
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d:ro

php-mysql:
  image: daocloud.io/library/mysql:5.7.18
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD="yourpwd"
    - MYSQL_DATABASE="yourdb"
